// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwvkEPNI7ZjGgaUFYfPhneUFGOAeQdxG0',
    appId: '1:150169113255:web:7ce9953ba817a22f8a8182',
    messagingSenderId: '150169113255',
    projectId: 'budaya-bengkulu-34fe6',
    authDomain: 'budaya-bengkulu-34fe6.firebaseapp.com',
    databaseURL:
        'https://budaya-bengkulu-34fe6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'budaya-bengkulu-34fe6.firebasestorage.app',
    measurementId: 'G-T3NE10DH3F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZ5seev6HSq-L3Ko_OmzHlvEVPFjU3LxM',
    appId: '1:150169113255:android:2b8ab4a8857009f88a8182',
    messagingSenderId: '150169113255',
    projectId: 'budaya-bengkulu-34fe6',
    databaseURL:
        'https://budaya-bengkulu-34fe6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'budaya-bengkulu-34fe6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3OMGcD1v94W1KBA-01XjEe3Se07IKptU',
    appId: '1:150169113255:ios:7302ddac06ddefd58a8182',
    messagingSenderId: '150169113255',
    projectId: 'budaya-bengkulu-34fe6',
    databaseURL:
        'https://budaya-bengkulu-34fe6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'budaya-bengkulu-34fe6.firebasestorage.app',
    iosBundleId: 'com.example.budayaBengkulu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3OMGcD1v94W1KBA-01XjEe3Se07IKptU',
    appId: '1:150169113255:ios:7302ddac06ddefd58a8182',
    messagingSenderId: '150169113255',
    projectId: 'budaya-bengkulu-34fe6',
    databaseURL:
        'https://budaya-bengkulu-34fe6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'budaya-bengkulu-34fe6.firebasestorage.app',
    iosBundleId: 'com.example.budayaBengkulu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwvkEPNI7ZjGgaUFYfPhneUFGOAeQdxG0',
    appId: '1:150169113255:web:80035ffb39953f548a8182',
    messagingSenderId: '150169113255',
    projectId: 'budaya-bengkulu-34fe6',
    authDomain: 'budaya-bengkulu-34fe6.firebaseapp.com',
    databaseURL:
        'https://budaya-bengkulu-34fe6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'budaya-bengkulu-34fe6.firebasestorage.app',
    measurementId: 'G-2H24ZLB4C3',
  );
}
